import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "../components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <div className="flex justify-center h-full">
          {/* Left Sidebar */}
          <div className="fixed left-0 top-0 w-[250px] px-4 hidden lg:block h-full">
            <Sidebar />
          </div>
          {/* Main Content */}
          <div className="flex-1 max-w-[600px] px-4 h-full lg:ml-[250px] lg:mr-[330px]">
            {children}
          </div>
          {/* Right Sidebar */}
          <div className="fixed right-0 top-0 w-[330px] hidden lg:block px-4 h-full">
            Right Sidebar
          </div>
        </div>
      </body>
    </html>
  );
}
